[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
lib_deps = 
	adafruit/Adafruit PWM Servo Driver Library @ ^3.0.1
	https://github.com/rodneybakiskan/ps5-esp32.git